"use client";
import {useEffect,useState} from "react";
const CA="0x9c69a66e814198a4bf60b9e6712f06fa22001600";
const DEX="https://radardex.pro/#0x9c69a66e814198a4bf60b9e6712f06fa22001600";
const X="https://x.com/Buildog_";
const DOG="https://buildog.xyz/dog.png";
export default function Home(){const[copied,setCopied]=useState(false);const copy=async()=>{await navigator.clipboard.writeText(CA);setCopied(true);setTimeout(()=>setCopied(false),1400)};useEffect(()=>{const els=[...document.querySelectorAll(".reveal")];const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add("show")),{threshold:.12});els.forEach(e=>io.observe(e));return()=>io.disconnect()},[]);return <main>
<header className="nav"><a className="logo" href="#">$BUILDOG</a><nav><a href="#lore">lore</a><a href="#facts">facts</a><a href="#token">token</a></nav><a className="buy mini" href={DEX} target="_blank">🦴 buy $BUILDOG</a></header>
<section className="hero"><div className="heroCopy reveal show"><div className="kicker">shipped on arc · goodest builder · hackathon born</div><h1>THE BUILDER<br/><span>WAS IN THE ROOM.</span></h1><p>227 teams shipped at the Arc hackathon.<br/>One of them had four legs and a hat.</p><div className="heroBtns"><a className="buy" href={DEX} target="_blank">🦴 BUY $BUILDOG</a><a className="paperBtn" href="#lore">📜 READ THE LORE</a></div><div className="ca"><span>CA</span><code>{CA}</code><button onClick={copy}>{copied?"COPIED ✓":"COPY"}</button></div></div>
<div className="dogCard reveal show"><div className="tape">THE BUILDER</div><img src={DOG} alt="Buildog at the hackathon"/><div className="caption">real dog. real hat. real timeline.</div></div></section>
<div className="marquee"><div>$BUILDOG · NOT A BULLDOG. A BUILDOG. · THE BUILDER WAS IN THE ROOM · ZERO UTILITY, FULL LOYALTY · KEEP SHIPPING · </div></div>
<section id="lore" className="lore reveal"><div className="sectionLabel">📜 THE LORE</div><h2>EVERY HACKATHON HAS WINNERS.<br/><span>THIS ONE HAD A BUILDER.</span></h2><div className="loreGrid"><div><p>227 teams. AI agents paying each other in sub-cent USDC. Oracles, ad exchanges, new payment rails. The future of the internet economy, built in one weekend.</p><p>And in the middle of it all — photographed, documented, undeniable — a dog. Wearing the hat. Posted by the chain itself. Seen by the timeline.</p><p><b>The humans got the prizes. The dog got the timeline — and a name: Buildog.</b></p></div><aside><div className="receipt">RECEIPT #227</div><img src={DOG} alt="Buildog proof"/><strong>PHOTOGRAPHIC EVIDENCE ✓</strong><small>the goodest builder was actually there.</small></aside></div></section>
<section id="facts" className="facts reveal"><div className="sectionLabel">🐾 BUILDOG FACTS</div><div className="factGrid"><article className="yellow"><b>227</b><span>TEAMS BUILDING</span><small>one had paws.</small></article><article className="blue"><b>1</b><span>DOG ON DUTY</span><small>attendance: perfect.</small></article><article className="pink"><b>∞</b><span>TREATS DESERVED</span><small>non-negotiable.</small></article><article className="green"><b>$BUILDOG</b><span>TICKER ACQUIRED</span><small>community assigned.</small></article></div></section>
<section className="creed reveal"><div className="terminal"><div>buildog@arc:~/creed</div><p>✓ zero complicated utility<br/>✓ 100% dog<br/>✓ backed by photographic evidence<br/>✓ native to Arc<br/>✓ ships while you sleep</p></div><div><div className="sectionLabel">WHY BUILDOG?</div><h2>HE DIDN'T WIN<br/>THE HACKATHON.<br/><span>HE WON THE TIMELINE.</span></h2><p>Buildog doesn't pitch VCs. Buildog doesn't write whitepapers. Buildog shows up, wears the hat, and ships.</p></div></section>
<section id="token" className="token reveal"><div className="sectionLabel">🦴 THE TOKEN</div><h2>$BUILDOG</h2><div className="tokenBox"><div><span>NETWORK</span><b>ARC</b></div><div><span>TICKER</span><b>$BUILDOG</b></div><div className="wide"><span>CONTRACT</span><code>{CA}</code><button onClick={copy}>{copied?"COPIED ✓":"COPY"}</button></div></div><div className="heroBtns center"><a className="buy" href={DEX} target="_blank">BUY ON RADARDEX ↗</a><a className="paperBtn" href={X} target="_blank">FOLLOW ON X</a></div></section>
<section className="final reveal"><div className="bubble">good boy.</div><h2>KEEP BUILDING.</h2><p>the builder the leaderboard forgot.<br/>the ticker the timeline demanded.</p><a className="buy" href={DEX} target="_blank">🦴 BUY $BUILDOG</a></section>
<footer><b>$BUILDOG</b><span>community meme on Arc</span><div><a href={X} target="_blank">𝕏 twitter</a><a href={DEX} target="_blank">radardex</a></div><small>$BUILDOG is a community meme token. Always do your own research.</small></footer>
</main>}