"use client";
import {useEffect,useState} from "react";
const CA="0x9c69a66e814198a4bf60b9e6712f06fa22001600";
const DEX="https://radardex.pro/#0x9c69a66e814198a4bf60b9e6712f06fa22001600";
const X="https://x.com/Buildog_";
const TG="https://t.me/buildogchat";
const DOG="https://buildog.xyz/dog.png";
export default function Home(){const[copied,setCopied]=useState(false);const copy=async()=>{await navigator.clipboard.writeText(CA);setCopied(true);setTimeout(()=>setCopied(false),1400)};useEffect(()=>{const els=[...document.querySelectorAll(".reveal")];const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add("show")),{threshold:.12});els.forEach(e=>io.observe(e));return()=>io.disconnect()},[]);return <main>
<header className="nav"><a className="logo" href="#">$BUILDOG <span className="ogMini">OG</span></a><nav><a href="#lore">lore</a><a href="#cto">cto</a><a href="#proof">proof</a><a href="#token">token</a></nav><a className="buy mini" href={DEX} target="_blank">🦴 buy $BUILDOG</a></header>
<section className="hero"><div className="heroCopy reveal show"><div className="kicker">THE OG BUILDOG · COMMUNITY TAKEOVER · ARC HACKATHON BORN</div><div className="ogBadge">✓ ORIGINAL BUILDOG</div><h1>THE BUILDER<br/><span>WAS IN THE ROOM.</span></h1><p>The original Buildog from the real Arc hackathon moment. The creator stepped away. The community stayed.</p><div className="heroBtns"><a className="buy" href={DEX} target="_blank">🦴 BUY THE OG</a><a className="paperBtn" href={X} target="_blank">𝕏 X / TWITTER</a><a className="paperBtn" href={TG} target="_blank">✈ TELEGRAM</a></div><div className="ca ogCa"><span>OG CA</span><code>{CA}</code><button onClick={copy}>{copied?"COPIED ✓":"COPY"}</button></div><small className="caNote">THIS IS THE ORIGINAL BUILDOG CONTRACT. VERIFY BEFORE YOU BUY.</small></div>
<div className="dogCard reveal show"><div className="tape">THE OG BUILDER</div><img src={DOG} alt="The original Buildog at the hackathon"/><div className="caption">real dog. real hackathon. original ticker story.</div></div></section>
<div className="marquee"><div>THE OG $BUILDOG · COMMUNITY TAKEOVER · ORIGINAL CONTRACT · REAL HACKATHON STORY · THE BUILDER WAS IN THE ROOM · </div></div>
<section id="lore" className="lore reveal"><div className="sectionLabel">📜 THE LORE</div><h2>THE STORY CAME FIRST.<br/><span>THE TICKER CAME AFTER.</span></h2><div className="loreGrid"><div><p>227 teams showed up to build at the Arc hackathon. AI agents, payment rails, markets and infrastructure shipped in one weekend.</p><p>In the middle of it all was a dog wearing the builder hat — photographed, posted and seen across the timeline.</p><p><b>The humans got the prizes. The dog got the story. The community gave him a ticker: $BUILDOG.</b></p></div><aside><div className="receipt">ORIGINAL RECEIPT</div><img src={DOG} alt="Original Buildog proof"/><strong>PHOTOGRAPHIC EVIDENCE ✓</strong><small>the meme existed before the takeover.</small></aside></div></section>
<section id="cto" className="cto reveal"><div className="sectionLabel">🤝 COMMUNITY TAKEOVER</div><div className="ctoGrid"><div><h2>THE CREATOR<br/>STEPPED AWAY.<br/><span>THE COMMUNITY DIDN'T.</span></h2></div><div className="ctoCard"><div className="ctoStamp">CTO ACTIVE</div><p>The original token was left without attention.</p><p>So the community picked up the story, the socials and the mission.</p><p><b>No reset. No new ticker. The OG Buildog continues.</b></p><div className="heroBtns"><a className="paperBtn" href={TG} target="_blank">JOIN THE CTO</a><a className="paperBtn" href={X} target="_blank">FOLLOW THE OG</a></div></div></div></section>
<section id="proof" className="proof reveal"><div className="sectionLabel">🧾 OG PROOF</div><h2>ONE STORY.<br/><span>ONE ORIGINAL CONTRACT.</span></h2><div className="timeline"><article><small>01</small><b>ARC HACKATHON</b><p>Buildog appears in the real event photo.</p></article><article><small>02</small><b>ORIGINAL TOKEN</b><p>The first $BUILDOG ticker is launched around the story.</p></article><article><small>03</small><b>CREATOR GOES QUIET</b><p>The project stops receiving active attention.</p></article><article><small>04</small><b>COMMUNITY TAKEOVER</b><p>The community takes over and keeps the OG alive.</p></article></div><div className="ogContract"><div><span>OG CONTRACT</span><strong>{CA}</strong></div><button onClick={copy}>{copied?"COPIED ✓":"COPY OG CA"}</button></div></section>
<section id="facts" className="facts reveal"><div className="sectionLabel">🐾 BUILDOG FACTS</div><div className="factGrid"><article className="yellow"><b>227</b><span>TEAMS BUILDING</span><small>one had paws.</small></article><article className="blue"><b>1</b><span>OG BUILDOG</span><small>the original story.</small></article><article className="pink"><b>CTO</b><span>COMMUNITY LED</span><small>the story continues.</small></article><article className="green"><b>1 CA</b><span>VERIFY THE OG</span><small>don't trust the name alone.</small></article></div></section>
<section className="creed reveal"><div className="terminal"><div>buildog@arc:~/status</div><p>✓ original hackathon story<br/>✓ original $BUILDOG contract<br/>✓ community takeover active<br/>✓ official X + Telegram live<br/>✓ still shipping</p></div><div><div className="sectionLabel">WHY THE OG?</div><h2>OTHERS CAN COPY<br/>THE NAME.<br/><span>NOT THE ORIGIN.</span></h2><p>The point isn't to be the loudest Buildog. It's to preserve the one that came from the actual moment.</p></div></section>
<section id="token" className="token reveal"><div className="sectionLabel">🦴 VERIFY BEFORE YOU BUY</div><h2>$BUILDOG</h2><div className="tokenBox"><div><span>STATUS</span><b>OG / CTO</b></div><div><span>NETWORK</span><b>ARC</b></div><div className="wide"><span>ORIGINAL CONTRACT</span><code>{CA}</code><button onClick={copy}>{copied?"COPIED ✓":"COPY"}</button></div></div><div className="heroBtns center"><a className="buy" href={DEX} target="_blank">BUY ON RADARDEX ↗</a><a className="paperBtn" href={X} target="_blank">OFFICIAL X</a><a className="paperBtn" href={TG} target="_blank">OFFICIAL TELEGRAM</a></div></section>
<section className="official reveal"><div className="sectionLabel">🔗 OFFICIAL LINKS</div><h2>DON'T GUESS.<br/><span>USE THE OFFICIALS.</span></h2><div className="linkGrid"><a href={X} target="_blank"><b>𝕏 X / TWITTER</b><span>@Buildog_</span></a><a href={TG} target="_blank"><b>✈ TELEGRAM</b><span>buildogchat</span></a><a href={DEX} target="_blank"><b>🦴 RADARDEX</b><span>trade the OG</span></a><button onClick={copy}><b>📋 OG CONTRACT</b><span>{copied?"copied ✓":"copy address"}</span></button></div></section>
<section className="final reveal"><div className="bubble">community takeover.</div><h2>KEEP THE OG BUILDING.</h2><p>The creator left. The story didn't.<br/>Join the community carrying the original Buildog forward.</p><div className="heroBtns center"><a className="buy" href={TG} target="_blank">JOIN THE CTO</a><a className="paperBtn" href={DEX} target="_blank">BUY $BUILDOG</a></div></section>
<footer><b>$BUILDOG <span className="footerOg">OG</span></b><span>community takeover on Arc</span><div><a href={X} target="_blank">𝕏 twitter</a><a href={TG} target="_blank">telegram</a><a href={DEX} target="_blank">radardex</a></div><small>Always verify the contract address. $BUILDOG is a community meme token. Do your own research.</small></footer>
</main>}